### ISSUE TITLE
back to back friendbot requests, different addresses, second fails

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/horizon#12]
```
Started GET "/friendbot/?addr=gSvocTAmy31bgVAKnp7UDKwDBNVYTkG2JWib4tJmp3TF7vBjS5" for 0:0:0:0:0:0:0:1 at 2015-03-31 17:55:47 -0700
Processing by TransactionsController#friendbot as */*
  Parameters: {"addr"=>"gSvocTAmy31bgVAKnp7UDKwDBNVYTkG2JWib4tJmp3TF7vBjS5"}
  History::Transaction Load (1.0ms)  SELECT  "history_transactions".* FROM "history_transactions"  WHERE "history_transactions"."transaction_hash" = '094a031ca9ccfaf709bf2043a81c04fee12f3896c256f957f8acf87f44a55313'  ORDER BY "history_transactions"."id" ASC LIMIT 1
  Hayashi::Transaction Load (1.0ms)  SELECT  "txhistory".* FROM "txhistory"  WHERE "txhistory"."txid" = '094a031ca9ccfaf709bf2043a81c04fee12f3896c256f957f8acf87f44a55313'  ORDER BY "txhistory"."txid" ASC LIMIT 1
get http://localhost:39132/tx?blob=2e3c35010749c1de3d9a5bdd6a31c12458768da5ce87cca6aad63ebbaaef74320000000a000000000000000100000000ffffffff0000000100000000000000003adf34c60f9b88a1e76f41376d4169dece96471580f426786ad224c446ae15e8000000000000000005f5e1000000000000000000000000000000000005f5e100000000012e3c35010c555c03378b5b238930a99127681c955d50212f0d599643e05d7ff4a79d22adcb23808ce8b40117768e4bf489f9e95d1f213cd2005fa2b6d6d31b844c42670b
User-Agent: "Faraday v0.9.1"
200
content-length: "90"
content-type: "application/json"
Completed 201 Created in 34ms (Views: 1.0ms | ActiveRecord: 0.0ms)





Started GET "/accounts/gSvocTAmy31bgVAKnp7UDKwDBNVYTkG2JWib4tJmp3TF7vBjS5" for 0:0:0:0:0:0:0:1 at 2015-03-31 17:56:05 -0700
Processing by AccountsController#show as */*
  Parameters: {"id"=>"gSvocTAmy31bgVAKnp7UDKwDBNVYTkG2JWib4tJmp3TF7vBjS5"}
  Hayashi::Account Load (1.0ms)  SELECT  "accounts".* FROM "accounts"  WHERE "accounts"."accountid" = 'gSvocTAmy31bgVAKnp7UDKwDBNVYTkG2JWib4tJmp3TF7vBjS5'  ORDER BY "accounts"."accountid" ASC LIMIT 1
  Hayashi::TrustLine Load (1.0ms)  SELECT "trustlines".* FROM "trustlines"  WHERE "trustlines"."accountid" = 'gSvocTAmy31bgVAKnp7UDKwDBNVYTkG2JWib4tJmp3TF7vBjS5'
Completed 200 OK in 20ms (Views: 5.0ms | ActiveRecord: 10.0ms)


Started GET "/friendbot/?addr=gsvVbqVTtx8GHNdCdmgwMS4C5T8sUWeyDFDH1rQwkNicdHaW7mo" for 0:0:0:0:0:0:0:1 at 2015-03-31 17:57:38 -0700
Processing by TransactionsController#friendbot as */*
  Parameters: {"addr"=>"gsvVbqVTtx8GHNdCdmgwMS4C5T8sUWeyDFDH1rQwkNicdHaW7mo"}
Actor crashed!
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `wait_poll'
	org/jruby/RubyKernel.java:1507:in `loop'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `poll'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in `synchronize'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `poll'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in `acquire_connection'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `checkout'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `connection'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/composite_primary_keys-7.0.13/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:48:in `retrieve_connection'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/composite_primary_keys-7.0.13/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:30:in `connection'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:48:in `connection'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation/query_methods.rb:856:in `build_arel'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation/query_methods.rb:842:in `arel'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation.rb:611:in `exec_queries'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation.rb:493:in `load'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation.rb:238:in `to_a'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation/finder_methods.rb:474:in `find_nth_with_limit'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation/finder_methods.rb:468:in `find_nth'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/activerecord-4.1.9/lib/active_record/relation/finder_methods.rb:132:in `first'
	/Users/andrewrogers/Code/stellar/horizon/app/models/transaction_submission.rb:106:in `history_transaction'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/memoist-0.11.0/lib/memoist.rb:147:in `history_transaction'
	/Users/andrewrogers/Code/stellar/horizon/app/models/transaction_submission.rb:89:in `finished?'
	/Users/andrewrogers/Code/stellar/horizon/app/models/transaction_submission.rb:52:in `process'
	/Users/andrewrogers/Code/stellar/horizon/lib/instrumentation.rb:62:in `process_with_instrumentation'
	org/jruby/RubyProc.java:271:in `call'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/metriks-0.9.9.7/lib/metriks/timer.rb:51:in `time'
	/Users/andrewrogers/Code/stellar/horizon/lib/instrumentation.rb:61:in `process_with_instrumentation'
	/Users/andrewrogers/Code/stellar/horizon/app/models/friendbot.rb:29:in `pay'
	org/jruby/RubyKernel.java:1958:in `public_send'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `invoke'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `task'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `task'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `initialize'
	/Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `create'
	(celluloid):0:in `remote procedure call'
Completed 500 Internal Server Error in 5007ms
  Hayashi::Account Load (1.0ms)  SELECT  "accounts".* FROM "accounts"  WHERE "accounts"."accountid" = 'gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7'  ORDER BY "accounts"."accountid" ASC LIMIT 1

ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)):
  app/models/transaction_submission.rb:106:in `history_transaction'
  app/models/transaction_submission.rb:89:in `finished?'
  app/models/transaction_submission.rb:52:in `process'
  lib/instrumentation.rb:62:in `process_with_instrumentation'
  lib/instrumentation.rb:61:in `process_with_instrumentation'
  app/models/friendbot.rb:29:in `pay'
  app/controllers/transactions_controller.rb:71:in `friendbot'
  lib/request_metrics.rb:16:in `call'


  Rendered /Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.0ms)
  Rendered /Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendered /Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.0ms)
  Rendered /Users/andrewrogers/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/actionpack-4.1.9/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (23.0ms)

```

**Comment by nullstyle** [comment]
This should have been solved with the connection leak fix.  Closing, until we see it again.
