### ISSUE TITLE
asset name > 3

### ISSUE THREAD

**Issue by FredericHeem** [stellar/horizon#36]
Horizon doesn't support yet the 12 character asset name:

RuntimeError: Unknown asset type: Stellar::AssetType.asset_type_credit_alphanum12(2)
        /home/ubuntu/horizon/app/jobs/history/ledger_importer_job.rb:451:in `asset_details'
        /home/ubuntu/horizon/app/jobs/history/ledger_importer_job.rb:251:in `block in import_history_operations'
        /home/ubuntu/horizon/app/jobs/history/ledger_importer_job.rb:109:in `each'
        /home/ubuntu/horizon/app/jobs/history/ledger_importer_job.rb:109:in `each_with_index'

**Comment by FredericHeem** [comment]
Solve in PR https://github.com/stellar/horizon/pull/37

**Comment by FredericHeem** [comment]
fixed in PR https://github.com/stellar/horizon/pull/37
